config/routes.rb
Rails.application.routes.draw do



  root to: 'pages#home'

  # get 'favourites/new'
  # get 'favourites/create'
  # get 'favourites/index'
  # get 'favourites/edit'
  # get 'favourites/update'
  # get 'favourites/show'
  # get 'favourites/destroy'
  resources :favourites

  # get 'notes/new'
  # get 'notes/create'
  # get 'notes/index'
  # get 'notes/edit'
  # get 'notes/update'
  # get 'notes/show'
  # get 'notes/destroy'
  resources :notes

  #get 'jobs/new'
  # get 'jobs/create'
  # get 'jobs/index'
  # get 'jobs/edit'
  # get 'jobs/update'
  # get 'jobs/show'
  # get 'jobs/destroy'
  get 'jobs/external' => 'jobs#external'
  resources :jobs

  # get 'users/new'
  # get 'users/create'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/show'
  # get 'users/destroy'
  get 'users/juniors' => 'users#juniors'
  get 'users/companies' => 'users#companies'
  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  #get '/admin'   => 'pages#admin_party'

  namespace :admin do
    resources :favourites
    resources :jobs
    resources :notes
    resources :users

    root to: "favourites#index"
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id            :integer          not null, primary key
#  title         :text
#  description   :text
#  job_location  :text
#  job_date      :text
#  job_company   :text
#  contract_type :text
#  logo_image    :text
#  salary        :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#

class Job < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :users, through: :favourites
end

app/controllers/admin/jobs_controller.rb
module Admin
  class JobsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Job.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Job.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :check_if_logged_in, except: [:index, :external, :show]

  def new

    #if @current_user.user_type? :manager
      #user = User.find_by user_type: 'employer'
    if @current_user.user_type == "employer"
      @job = Job.new
    else
      flash[:error] = "Only employers can post jobs"
      redirect_to login_path
    end

    @job_list = Job.where(user_id: @current_user.id)
  end

  def create

    # job = Job.create(job_params)
    job = @current_user.jobs.create job_params
    # raise 'hell'
    redirect_to job_path job

  end

  def index
    @jobs = Job.all
    @favourite_list = if @current_user != nil then Favourite.where user_id:@current_user.id else nil end
    # @favourite = Favourite.where user_id: @current_user.id, job_id: @jobs.id
  end

  def external
    #OLD URL https://www.googleapis.com/books/v1/volumes?q=title:#{ params[:text_query] }
    search_url = "https://api.adzuna.com:443/v1/api/jobs/au/search/1?app_id=95ee4265&app_key=2354363480da7233eb45e9cd61258be5&results_per_page=20&what_or=Junior%2C%20Jnr%2C%20jr&category=IT-Jobs&sort_direction=down&sort_by=date
"


    results = HTTParty.get search_url
    # cl results
    @results = results['results']


  end

  def edit
    job = Job.find params[:id]

    if @current_user.user_type == "employer" && @current_user.id == job.user.id
      @job = Job.find params[:id]


    else
      flash[:error] = "You are not authorised to edit this job"
      redirect_to login_path
    end

  end

  def update
    job = Job.find params[:id]
      job.update job_params
      redirect_to job
  end

  def show
    @job = Job.find params[:id]
    @user = User.find @job.user_id
    @favourite = if @current_user != nil then Favourite.where user_id: @current_user.id, job_id: @job.id else nil end
    #raise 'hell'
    #
    # template = @current_user.user_type + "_show"
    # render template
  end

  def destroy
    Job.destroy params[:id]
    redirect_to job_path
  end

  private
  # strong params for the artist form submit
  def job_params

    params.require(:job).permit(:title, :description, :job_location, :job_date, :job_company, :contract_type, :logo_image, :salary, :user_id)

  end


end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
    <%= form_for @job do |f| %>
      <fieldset>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </fieldset>
      <fieldset>
        <%= f.label :description %>
        <%= f.text_field :description %>
      </fieldset>
      <fieldset>
        <%= f.label :job_location %>
        <%= f.text_field :job_location %>
      </fieldset>
      <fieldset>
        <%= f.label :job_date %>
        <%= f.date_field :job_date %>
      </fieldset>
      <fieldset>
        <%= f.label :job_company %>
        <%= f.text_field :job_company %>
      </fieldset>
      <fieldset>
        <%= f.label :contract_type %>
        <%= f.text_field :contract_type %>
      </fieldset>
      <fieldset>
        <%= f.label :logo_image, 'image URL' %>
        <%= f.text_field :logo_image %>
      </fieldset>
      <fieldset>
        <%= f.label :salary %>
        <%= f.text_field :salary %>
      </fieldset>


      <%= f.submit 'Save' %>

    <% end %>

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/destroy.html.erb
<h1>Jobs#destroy</h1>
<p>Find me in app/views/jobs/destroy.html.erb</p>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>
<%= render partial: 'form' %>

app/views/jobs/external.html.erb
<h1>EXTERNAL JOB BOARD</h1>

    <div class="wrapper">
      <div class="mdl-grid--no-spacing">
        <% @results.each do |job| %>
          <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--6-col-tablet mdl-cell--2-col-phone">
            <div class="mdl-card mdl-shadow--2dp mdl-card--horizontal">
              <div class="mdl-card__media">
                <!-- <img src="http://placehold.it/150x200/DC143C/FFFFFF" alt="img"> -->
                <img src="https://zunastatic-abf.kxcdn.com/images/global/jobs/fb_share.png" alt="img">
              </div>
                <div class="mdl-card__title">
                  <a href="<%= job['redirect_url'] %>">
                    <h4 class="mdl-card__title-text"><%= job['title'].gsub(/\<strong\>/, '').gsub(/\<\/strong\>/, '') %></h4><h4 class="mdl-card__title-text co">@ <%= job['company']['display_name'] %></h4>

                  </a>

                </div>
                <div class="mdl-card__supporting-text">
                  <%= job['description'].gsub(/\<strong\>/, '').gsub(/\<\/strong\>/, '') %>
                </div>
                <div class="mdl-card__actions mdl-card--border">
                  <a href="<%= job['redirect_url'] %>" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" data-upgraded="MaterialButton,MaterialRipple">Read More</a>
                  <span class="job-location"> <%= job['location']['display_name'] %></span>
                  <span class='job-date'><%= job['created'].gsub(/T........Z/, '') %></span>
                </div>
                <div class="mdl-card__menu">
                  <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" data-upgraded="MaterialButton,MaterialRipple"><i class="material-icons heart">favorite_border</i></button>
                </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

app/views/jobs/index.html.erb
<h1>JOB BOARD</h1>


    <div class="wrapper">
      <div class="mdl-grid--no-spacing">
        <% @jobs.each do |job| %>
          <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--6-col-tablet mdl-cell--2-col-phone">
            <div class="mdl-card mdl-shadow--2dp mdl-card--horizontal">
              <div class="mdl-card__media">
                <img src="<%= job.logo_image %>" alt="img">
                <!-- <img src="https://i.imgur.com/gafefiK.png" alt="img"> -->
              </div>
                <a href="jobs/<%= job.id %>"><div class="mdl-card__title">
                  <h4 class="mdl-card__title-text"><%= job.title %></h4><h4 class="mdl-card__title-text co">@ <%= job.job_company %></h4>

                </div></a>
                <div class="mdl-card__supporting-text">
                  <%= truncate(job.description, :length => 330)  %>
                </div>
                <div class="mdl-card__actions mdl-card--border">
                  <a href="jobs/<%= job.id %>" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" data-upgraded="MaterialButton,MaterialRipple">Read More</a>
                  <span class="job-location"> <%= job.job_location %></span>
                  <span class='job-date'><%= job.job_date %></span>
                </div>
                <div class="mdl-card__menu">
                  <%= link_to favourites_path(user_id: @current_user != nil ? @current_user.id : nil, job_id: job.id), class: 'mdl-button mdl-js-button mdl-button--icon mdl-button--colored', method: :post do%>
                    <% if @favourite_list.present? && @favourite_list.find{|rec| rec.job_id == job.id}%>
                      <i class="material-icons">favorite</i>
                    <%else %>
                      <i class="material-icons">favorite_border</i>
                    <% end %>
                  <% end %>
                </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

app/views/jobs/new.html.erb
<h1>JOB CONSOLE</h1>


<div class="mdl-grid new-job">
  <ul class="demo-list-three mdl-list">
    <h2>MY JOBS</h2>
    <% @job_list.each do |job| %>
      <li class="mdl-list__item mdl-list__item--three-line">
        <span class="mdl-list__item-primary-content">
          <img src="job.logo_image" alt="">
          <strong>Job ID: </strong><span><%= job.id %></span>
          <a href="jobs/<%= job.id %>"><strong><span><%= job.title %></span></strong></a>
          <span class="mdl-list__item-text-body">
            <%= job.description %>
          </span>
        </span>
        <span class="mdl-list__item-secondary-content">
          <a href="jobs/<%= job.id %>/edit">Edit</a><a href="jobs/<%= job.id %>/delete">Delete</a>
        </span>
      </li>
    <% end %>
  </ul>
    <div class="mdl-cell mdl-cell--3-col ">
      <h2>NEW JOB</h2>
      <div class="show-box">
          <%= render partial: 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<div class="profile-edit">
   <% if @current_user != nil && @current_user.id == @job.user_id %> <%= link_to 'Edit', edit_job_path( @job )%>
<%= link_to 'Delete', job_path( @job.id ), confirm: 'Are you sure?', method: :delete %>
   <% end %>
</div>

<div class="mdl-grid job-show">
  <div class="mdl-cell mdl-cell--4-col">
    <div class="profile">
      <img src="<%= @job.logo_image %>" alt="">
      <h5><%= @job.id %></h5>
      <h5><%= @job.title %></h5>
      <li><p><%= @job.job_date %> <%= @job.job_company %></p></li>
      <li><p><%= @job.contract_type %></p></li>
      <li><p><%= @job.salary %></p></li>
    </div>

  </div>

  <div class="mdl-cell mdl-cell--8-col">
    <%= link_to favourites_path(user_id: @current_user != nil ? @current_user.id : nil, job_id: @job.id), class: 'mdl-button mdl-js-button mdl-button--icon mdl-button--colored', method: :post do%>
      <% if @favourite.present? %>
        <i class="material-icons">favorite</i>
      <%else %>
        <i class="material-icons">favorite_border</i>
      <% end %>
    <% end %>
    <div class="bio">
      <h6>Job Description</h6>
      <p><%= @job.description %></p>
    </div>
    <div class="Qualifications">
      <h6>Qualifications</h6>
      <p>blah</p>
    </div>
    <div class="Experience">
      <h6>Experience</h6>
      <p>blah blah</p>
    </div>
    <p>Post created at <%= @job.created_at %> by <%= @user.name %>
  </div>
</div>

app/views/jobs/update.html.erb
<h1>Jobs#update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>