config/routes.rb
Rails.application.routes.draw do



  root to: 'pages#home'

  # get 'favourites/new'
  # get 'favourites/create'
  # get 'favourites/index'
  # get 'favourites/edit'
  # get 'favourites/update'
  # get 'favourites/show'
  # get 'favourites/destroy'
  resources :favourites

  # get 'notes/new'
  # get 'notes/create'
  # get 'notes/index'
  # get 'notes/edit'
  # get 'notes/update'
  # get 'notes/show'
  # get 'notes/destroy'
  resources :notes

  #get 'jobs/new'
  # get 'jobs/create'
  # get 'jobs/index'
  # get 'jobs/edit'
  # get 'jobs/update'
  # get 'jobs/show'
  # get 'jobs/destroy'
  get 'jobs/external' => 'jobs#external'
  resources :jobs

  # get 'users/new'
  # get 'users/create'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/show'
  # get 'users/destroy'
  get 'users/juniors' => 'users#juniors'
  get 'users/companies' => 'users#companies'
  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  #get '/admin'   => 'pages#admin_party'

  namespace :admin do
    resources :favourites
    resources :jobs
    resources :notes
    resources :users

    root to: "favourites#index"
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favourite.rb
# == Schema Information
#
# Table name: favourites
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  job_id     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates :job, uniqueness: { scope: :user }
end

app/controllers/admin/favourites_controller.rb
module Admin
  class FavouritesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Favourite.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Favourite.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :check_if_logged_in




  def new
    @favourite = Favourite.new
  end

  def create

    Favourite.create user_id: params[:user_id], job_id: params[:job_id]
    redirect_to request.referrer
  end


  def update
  end

  def show
    # @favourite_list = if @current_user != nil then Favourite.where user_id:@current_user.id else nil end
    @favourite_list = Favourite.where(user_id: @current_user.id).select("job_id")
    @jobs = Job.where(id: @favourite_list)
    #raise 'hell'
    #@jobs = Jobs.where user_id:@favourite_list
  end

  def destroy
  end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/create.html.erb
<h1>Favourites#create</h1>
<p>Find me in app/views/favourites/create.html.erb</p>

app/views/favourites/destroy.html.erb
<h1>Favourites#destroy</h1>
<p>Find me in app/views/favourites/destroy.html.erb</p>

app/views/favourites/edit.html.erb
<h1>Favourites#edit</h1>
<p>Find me in app/views/favourites/edit.html.erb</p>

app/views/favourites/new.html.erb
<h1>Favourites#new</h1>
<p>Find me in app/views/favourites/new.html.erb</p>

app/views/favourites/show.html.erb
<h1>FAVOURITES</h1>

<div class="mdl-grid fav-list">
  <% @jobs.each do |favorite| %>

    <ul class="demo-list-three mdl-list">
      <li class="mdl-list__item mdl-list__item--three-line">
        <div class="list-title">
          <a href="<%= job_path %>"><span><%= favorite.title %></span></a>
          <span><%= favorite.job_date %></span>
          <span><%= favorite.job_company %></span>
        </div>
          <span class="mdl-list__item-text-body">
            <%= favorite.description %>
          </span>
        <span class="mdl-list__item-secondary-content">
          <a class="mdl-list__item-secondary-action" href="#"><i class="material-icons">favorite</i></a>
        </span>
      </li>
    </ul>
  <% end %>
</div>

app/views/favourites/update.html.erb
<h1>Favourites#update</h1>
<p>Find me in app/views/favourites/update.html.erb</p>